# Dockerfile for FastAPI Backend
FROM python:3.9

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
COPY /backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code
COPY backend/ /usr/src/app/


# Expose the port the app runs on
EXPOSE 8000

# Command to run the app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
